apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rideshare-frontend
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rideshare.ijeaweledivine.online
      secretName: tls-rideshare
  rules:
    - host: rideshare.ijeaweledivine.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rideshare-frontend
                port:
                  number: 80
