apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: rideshare-application
  region: eu-north-1
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      roleName: AmazonEBS_CSI_DriverRole  
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy  
